dist: xenial
language: python
python:
- '3.7'
before_install:
- touch ~/.ssh/id_rsa.pub
- echo ${Secret} >> ~/.ssh/id_rsa.pub
- cat ~/.ssh/id_rsa.pub
- git config --global user.name 'pynickle'
- git config --global user.email '2330458484@qq.com'
- git config --global credential.helper store
script:
- py.test study_program/test.py
- python interesting_program/test.py
- py.test what_the_fuck/test.py
- python study_program/auto_result.py
- git remote rm origin
- git remote add origin git@github.com:pynickle/amazing-python.git
- git add *
- git commit --allow-empty --quiet -m "update result"
- git push --force --quiet origin master
notifications:
  slack:
    on_success: never
    on_failure: never
install: true
